### ISSUE TITLE
An example observation

### ISSUE THREAD

**Issue by MatijaOgrin** [DARIAH-SI/Attems#1]
Florian: in the letter 8 (Mannheim, 24. 9. 1735), please check the point: 

> ihren ist herrn ist Voriges jahr ... 

 
I guess it should be: ihren `<del>ist</del>` herrn ist Voriges jahr ...

**Comment by andrejPancur** [comment]
Matija, you are right, in this case it would really be better to use: 

`ihren <del>ist</del> herrn ist Voriges jahr`

At the same time, I noticed that this error is also true in other similar cases. E.g. see the line later where you will notice: dönnerstag <del>war</del> speisete

In fact, the strikethrough words are already encoded in the TEI as 
`ihren <hi rend="strikeout">ist</hi> herrn ist Voriges jahr`

My suggestion: I would replace all these `//hi[@rend='strikeout']` with `del`. I can do this very quickly for the whole document.

**Comment by 10zeilinger** [comment]
Matija, Andrej, excuse my delay - and thank you for your observation! So del  is the better option. And as you say, Andrej, till now I used "hi rend="strikeout"" , so all these times it can be replaced with del. Would you do it (in this case: thank you!) - otherwise I can replace it as well?

**Comment by andrejPancur** [comment]
II just replaced it, so now it's sorted out and I'm closing the issue.
