### ISSUE TITLE
Two errors in the transcription

### ISSUE THREAD

**Issue by 10zeilinger** [DARIAH-SI/Attems#2]
Finally I am able to work with GitHub:

There are two words in the transcription, one that I misspelled and one that I forgot to tag:
l.10: it´s "propria" instead of "propriap"
l.20: "Surprenantes" has to be highlighted

I would like to correct them myself in Attems_letters.xml to start working with GitHub ("Edit this file") - please, just tell me if I shouldn´t do this because it would cause any damage.

**Comment by andrejPancur** [comment]
f you want to fix an XML file directly in GitHub, you can fix it with the "Edit this file" button without much danger. When you have finished making the desired corrections, you must make the message "Commit changes" below. Use radio button: Commit directly to the master branch. Matija and I will then download these changes to our computer (git pull).
